export const portfolioData = [
  {
    id: 1,
    title: "Direct & Silent Printing Applications for (Windows, MacOS)",
    img: "/img/weather.png",
    category: "product",
    link: "javascript:void(0)",
  },
  {
    id: 2,
    title: "FreightDesk Online Shopify Application",
    img: "/img/fdo_shop.png",
    category: "product",
    link: "https://apps.shopify.com/freightdesk-online-1",
  },
  {
    id: 3,
    title: "FreightDesk Online",
    img: "/img/fdo.png",
    category: "webApp",
    link: "https://freightdesk.online/",
  },
  {
    id: 4,
    title: "WordPress Plugins",
    img: "/img/fq.png",
    category: "product",
    link: "https://wordpress.org/plugins/search/eniture",
  },
  {
    id: 5,
    title: "HousePilot",
    img: "/img/Business-Website.png",
    category: "webApp",
    link: "https://housepilot.de/",
  },
  {
    id: 6,
    title: "ShoppingBin",
    img: "/img/Analog-Clock.png",
    category: "webApp",
    link: "https://shoppingbin.com/",
  },
  {
    id: 7,
    title: "Mondecheval",
    img: "/img/8e36ce60-76be-4a52-94c2-8f6e7593fb7e.avif",
    category: "webApp",
    link: "https://mondecheval-sa.com/",
  },
  {
    id: 7,
    title: "Kotore",
    img: "/img/Ecommerce Website.png",
    category: "webApp",
    link: "https://kotore.com/",
  },
  {
    id: 7,
    title: "Gardenia",
    img: "/img/shutterstock_756421564-1-1-1024x683.jpg",
    category: "webApp",
    link: "https://www.gardenia.net/",
  },
  {
    id: 7,
    title: "B&B Manufacturing",
    img: "/img/EarbIZhJUamJnkz6m2XW.jpg",
    category: "webApp",
    link: "https://bbmfg.com/",
  }
];
